### ISSUE TITLE
Total monthly bandwidth usage

### ISSUE THREAD

**Issue by G1lius** [FugueWeb/Scaling_Bitcoin#1]
I'd like to add total bandwidth usage to the balance as many people don't have access to non-capped bandwidth.

What should be the limit of what's acceptable and what would be the growth over time?  
I propose 200GB and 20% annually for pruned nodes. iirc comcast caps at 300GB, so 200GB seems like a good upper limit. In my country it hasn't increased 20% annually, but consumer demand for lots of data-usage is increasing a lot, so I think we can be optimistic.  
For full nodes it should be a limit where limit+'more than average usage' will start to raise red flags with providers. If I had to pick a number I'd pick 1TB +20% annually, but I don't have any data to back that up.

To estimate the total bandwidth usage after IBLT and for pruned nodes (as they don't serve historical blocks) it would be great to have some data on transaction relaying and block relaying separately, so if anyone has some data on this that would be great.

**Comment by FugueWeb** [comment]
Thanks for the feedback
